### ISSUE TITLE
S7: As a logged-in user, when I create a room, I want to edit the properties of the room so that I can enjoy the game

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs23-group-01/sopra-fs23-group-01-server#11]
# Acceptance Criteria

- [ ] As the creator of the room, I can set max number of players and the theme of the words for this game
- [ ] As the creator of the room, I can set the room to be private to play with friends or public to play with all players
- [ ] As the creator of the room, I can kick those players who do not come for playing
- [ ] As a player in the room, I can send a link to my friends to enter the game

# Development Tasks

- [x] sopra-fs23-group-01/sopra-fs23-group-01-client#18
- [x] sopra-fs23-group-01/sopra-fs23-group-01-server#88
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#90
- [x] sopra-fs23-group-01/sopra-fs23-group-01-server#91
