### ISSUE TITLE
S14: As a player, I want to know whether the game ends after each voting round so that we can determine whether we vote for the undercover.

### ISSUE THREAD

**Issue by zihanltesla** [sopra-fs23-group-01/sopra-fs23-group-01-server#12]
# Acceptance Criteria:

- [ ] After each voting round, the system should check whether the game ends.
- [ ] If there is no undercovers in the game, the system will announce that detectives have win the game.
- [ ] If the number of undercovers is equal to the number of detectives, the system will announce that undercovers have win the game.

# Development Tasks:
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#84
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#100
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-client#20
