### ISSUE TITLE
S16: As a user, I want the system to calculate my winning rate so that I can know my game history

### ISSUE THREAD

**Issue by zihanltesla** [sopra-fs23-group-01/sopra-fs23-group-01-server#16]
# Acceptance Criteria:

- [ ] When I finish one game, the system can include this game to calculate my winning according to my identity as an undercover or detective
- [ ] My winning rate can be displayed in my personal profile

# Development Taskes:
- [x] #36 
- [x] #92
- [x] #93
- [x] #103

**Comment by zihanltesla** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```
