### ISSUE TITLE
S1: As an unregistered user, I want to be able to register as a user with my chosen credentials to use services and information that are exclusively available to registered users.

### ISSUE THREAD

**Issue by zihanltesla** [sopra-fs23-group-01/sopra-fs23-group-01-server#3]
# Acceptance Criteria:

- [ ] Upon successful user registration, the user is redirected to the profile page of the site.
- [ ] Upon failure, an error is displayed, and the user is redirected (back) to the register screen. A register error can be that a username is already taken.
- [ ] The creation date of a user is saved to the database record.
- [ ] Logged-in users can log out and log back into their registered profile.

# Development Task:

- [ ] sopra-fs23-group-01/sopra-fs23-group-01-client#12
- [x] sopra-fs23-group-01/sopra-fs23-group-01-server#104
- [x] sopra-fs23-group-01/sopra-fs23-group-01-server#105
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-client#16
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#106
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#107
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-client#17
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#108
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#109
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#57
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#58

**Comment by yixuan-zhou-uzh** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```
