### ISSUE TITLE
S9: As a logged-in user, I want to start the game only after all players are ready so that I will not be busy while the game starts

### ISSUE THREAD

**Issue by Haaaan1** [sopra-fs23-group-01/sopra-fs23-group-01-server#9]
# Acceptance Criteria

- [ ] As a player in the room, I can click the ready button to be ready and I can also cancel ready

- [ ] As the creator of the room, I can only start the game after everyone is ready

# Development Tasks

- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#41
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-client#19
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#43
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#55
- [ ] sopra-fs23-group-01/sopra-fs23-group-01-server#56
